config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/contacts'
  get 'static_pages/about_us'
  get 'static_pages/payments'

  get '3b5fe44d4592.html' => "files#show"

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['ADMIN_LOGIN'] && password == ENV['ADMIN_PASSWORD']
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  resources :orders do
    member do
      post :repeat
      post :cancel
    end
  end

  get 'orders_exchange/1с' => 'orders#exchange_1с'

  resources :line_items do
    collection do
      get :add_to_cart
    end
  end

  namespace :payments do
    post :result
    post :success
    post :cancel
  end
  resources :carts

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}

  get '/account' => 'users#show', as: 'account'

  scope module: 'admin', path: 'admin' do
    resources :producers
    resources :messages
    resources :characteristic_names
    resources :characteristic_values
    resources :characteristics_group_vls
    resources :characteristics_group_rows
    resources :characteristics_groups
    resources :product_characteristics
    resources :posts
    resources :stocks
    resources :parts
    resources :people
    resources :discounts
    resources :home_page_banners
  end

  namespace :admin do
    resource :dashboard
    resources :deals
    resources :tizers
    resources :banners
    resources :orders do
      member do
        post :cancel
        post :ship
      end
    end
    resources :users
    resources :projects
    resources :coupons
    resources :special_offers
    resources :imports do
      collection do
        patch :proccess
      end
    end
    resources :products do
      collection do
        post :sort
      end
    end
    resources :categories do
      post :sort, on: :collection
      resources :products do
        post :sort, on: :collection
      end
    end
    resources :pages do
      post :sort, on: :collection
    end
    root 'categories#index'
  end
  # mount Ckeditor::Engine => '/ckeditor'
  resources :pages
  resources :deals, only: [:show, :index]
  resources :products, only: [:show] do
    collection do
      post :sort, :import
      get :compare, :import, :parser
    end
    member do
      get :add_to_compare, :remove_from_compare
    end
  end

  get :search, to: 'categories#search', as: 'searches'
  get 'searches/show'

  get 'wishlist/index'
  post 'wishlist/add_to_wishlist/:id' => 'wishlist#add_to_wishlist', as: 'add_to_wishlist'
  delete 'wishlist/destroy/:id' => 'wishlist#destroy', as: 'destroy_from_wishlist'

  post 'coupons/check' => 'coupons#check', as: 'coupons_check'

  post 'messages/create' => 'messages#create', as: 'create_message_from_form'
  post 'calculate_shipping/calculate' => 'calculate_shipping#calculate', as: 'calculate_shipping'
  post 'calculate_shipping/select_price_of_shipping' => 'calculate_shipping#select_price_of_shipping', as: 'select_price_of_shipping'
  get 'posts/show/:id' => 'posts#show', as: 'posts_show'
  get 'posts/index' => 'posts#index', as: 'posts_index'
  resources :categories, only: [:show, :index] do
    resources :products, only: [:show]
  end
  root 'welcome#index'
end

app/models/characteristics_group.rb
class CharacteristicsGroup < ActiveRecord::Base
  has_many :characteristics_group_rows
  has_many :products
end

app/controllers/admin/characteristics_groups_controller.rb
class Admin::CharacteristicsGroupsController < Admin::BaseController
  before_action :set_characteristics_group, only: [:show, :edit, :update, :destroy]

  # GET /characteristics_groups
  def index
    @characteristics_groups = CharacteristicsGroup.all
  end

  # GET /characteristics_groups/1
  def show
  end

  # GET /characteristics_groups/new
  def new
    @characteristics_group = CharacteristicsGroup.new
  end

  # GET /characteristics_groups/1/edit
  def edit
  end

  # POST /characteristics_groups
  def create
    @characteristics_group = CharacteristicsGroup.new(characteristics_group_params)

    if @characteristics_group.save
      redirect_to @characteristics_group, notice: 'Characteristics group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /characteristics_groups/1
  def update
    if @characteristics_group.update(characteristics_group_params)
      redirect_to @characteristics_group, notice: 'Characteristics group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /characteristics_groups/1
  def destroy
    @characteristics_group.destroy
    redirect_to characteristics_groups_url, notice: 'Characteristics group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristics_group
      @characteristics_group = CharacteristicsGroup.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def characteristics_group_params
      params.require(:characteristics_group).permit(:title)
    end
end

app/helpers/characteristics_groups_helper.rb
module CharacteristicsGroupsHelper
end

app/views/admin/characteristics_groups/_form.html.haml
= simple_form_for(@characteristics_group) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title

  .form-actions
    = f.button :submit, "Готово", class: 'btn btn-primary'

app/views/admin/characteristics_groups/edit.html.haml
= render 'form'

= link_to 'Показать все', characteristics_groups_path, class: 'btn btn-default'

app/views/admin/characteristics_groups/index.html.haml
%h1
  Группы характеристик
  = link_to 'Новая группа характеристик', new_characteristics_group_path, class: 'btn btn-success'

%table.table.table-stripped.table-bordered.datatable

  %thead
    %tr
      %th id
      %th Название
      / %th
      %th
      %th
  %tbody
    - @characteristics_groups.each do |characteristics_group|
      %tr
        %td= characteristics_group.id
        %td= characteristics_group.title
        / %td= link_to 'Показать', characteristics_group, class: 'btn btn-default'
        %td= link_to 'Редактировать', edit_characteristics_group_path(characteristics_group), class: 'btn btn-default'
        %td= link_to 'Удалить', characteristics_group, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/admin/characteristics_groups/new.html.haml
= render 'form'

= link_to 'Показать все', characteristics_groups_path, class: 'btn btn-default'

app/views/admin/characteristics_groups/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @characteristics_group.title

= link_to 'Edit', edit_characteristics_group_path(@characteristics_group)
\|
= link_to 'Back', characteristics_groups_path