config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/contacts'
  get 'static_pages/about_us'
  get 'static_pages/payments'

  get '3b5fe44d4592.html' => "files#show"

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['ADMIN_LOGIN'] && password == ENV['ADMIN_PASSWORD']
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  resources :orders do
    member do
      post :repeat
      post :cancel
    end
  end

  get 'orders_exchange/1с' => 'orders#exchange_1с'

  resources :line_items do
    collection do
      get :add_to_cart
    end
  end

  namespace :payments do
    post :result
    post :success
    post :cancel
  end
  resources :carts

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}

  get '/account' => 'users#show', as: 'account'

  scope module: 'admin', path: 'admin' do
    resources :producers
    resources :messages
    resources :characteristic_names
    resources :characteristic_values
    resources :characteristics_group_vls
    resources :characteristics_group_rows
    resources :characteristics_groups
    resources :product_characteristics
    resources :posts
    resources :stocks
    resources :parts
    resources :people
    resources :discounts
    resources :home_page_banners
  end

  namespace :admin do
    resource :dashboard
    resources :deals
    resources :tizers
    resources :banners
    resources :orders do
      member do
        post :cancel
        post :ship
      end
    end
    resources :users
    resources :projects
    resources :coupons
    resources :special_offers
    resources :imports do
      collection do
        patch :proccess
      end
    end
    resources :products do
      collection do
        post :sort
      end
    end
    resources :categories do
      post :sort, on: :collection
      resources :products do
        post :sort, on: :collection
      end
    end
    resources :pages do
      post :sort, on: :collection
    end
    root 'categories#index'
  end
  # mount Ckeditor::Engine => '/ckeditor'
  resources :pages
  resources :deals, only: [:show, :index]
  resources :products, only: [:show] do
    collection do
      post :sort, :import
      get :compare, :import, :parser
    end
    member do
      get :add_to_compare, :remove_from_compare
    end
  end

  get :search, to: 'categories#search', as: 'searches'
  get 'searches/show'

  get 'wishlist/index'
  post 'wishlist/add_to_wishlist/:id' => 'wishlist#add_to_wishlist', as: 'add_to_wishlist'
  delete 'wishlist/destroy/:id' => 'wishlist#destroy', as: 'destroy_from_wishlist'

  post 'coupons/check' => 'coupons#check', as: 'coupons_check'

  post 'messages/create' => 'messages#create', as: 'create_message_from_form'
  post 'calculate_shipping/calculate' => 'calculate_shipping#calculate', as: 'calculate_shipping'
  post 'calculate_shipping/select_price_of_shipping' => 'calculate_shipping#select_price_of_shipping', as: 'select_price_of_shipping'
  get 'posts/show/:id' => 'posts#show', as: 'posts_show'
  get 'posts/index' => 'posts#index', as: 'posts_index'
  resources :categories, only: [:show, :index] do
    resources :products, only: [:show]
  end
  root 'welcome#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  has_one :coupon

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def add_special_offer(special_offer_id)
    current_item = line_items.find_by(special_offer_id: special_offer_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(special_offer_id: special_offer_id)
    end
    current_item
  end

  def total_price (with_coupon = false)
    result = line_items.to_a.sum { |item| item.total_price }
    if with_coupon
      coupon ? result = result / 100 * (100 - coupon.amount) : nil
    end
    result
  end

end

app/controllers/carts_controller.rb
class CartsController < BaseController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @products = current_project.products.frontpageable.page params[:page]
    @best_seller = @products.first
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @cart }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end


  private
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}" 
      redirect_to root_url, notice: 'Invalid cart'
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
%table
  = render(cart.line_items)
  %tr.total_line
    %td{colspan: "2"} Итого
    %td.total_cell= number_to_currency(cart.total_price)

.row
  .span2= button_to "Оформить", new_order_path, method: :get, class: 'btn'
  .span1= button_to 'Очистить', cart, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn'

app/views/carts/_form.html.haml
= simple_form_for(@cart) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %tr
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
/ Breadcrumbs
%ol.breadcrumb
  %li
    %a{:href => "/"} Главная
  %li Корзина

/ Breadcrumbs Close
/ Shopping Cart
%section.shopping-cart
  .container
    .row
      / Items List
      .col-md-9
        %h2.title Моя Корзина
        .row
          .col-md-3
            Товары в корзине:
          .col-md-9
            .subnav
              = link_to 'готовые к заказу', cart_path
        %table.items-list
          %tbody
            %tr
              %th.col-md-5{colspan: 2} Товар
              %th.col-md-2 Цена
              %th{style: 'width: 100px !important'} Количество
              / %th{style: 'width: 50px !important'}
              %th.col-md-2
                %center
                  Действия
            - @cart.line_items.each do |li|
              - p = li.product
              - so = li.special_offer
              / Item
              %tr{ :class => "item first item_#{li.id}" }
                %td
                  - if p
                    = link_to p do
                      = image_tag p.image_url, class: 'img-thumbnail', width: 120
                %td.name
                  - if p
                    = link_to p.title, p
                  - elsif so
                    = link_to so.product_one.title, so.product_one
                    %br
                    +
                    %br
                    = link_to so.product_two.title, so.product_two
                  %br
                  / - li.line_item_characteristics.all.each do |characteristic|
                  /   = "#{characteristic.characteristic_name.title}: #{characteristic.characteristic_value.value}"
                  /   %br
                  = li.characteristics_from_offer
                %td.price.col-md-2
                  = number_to_currency li.price, unit: 'руб.'
                %td.qnt-count
                  = form_for(li, remote: true) do |f|
                    %a.incr-btn{:href => "#", data: {target: li.id}} -
                    - limit = li.offer_limit.present? ?  {limit: li.offer_limit} : {}
                    = f.text_field :quantity, class: 'quantity form-control', id: "line_item_quantity_#{li.id}", data: limit
                    / %input.quantity.form-control{:type => "text", :value => "2"}/
                    %a.incr-btn{:href => "#", data: {target: li.id}} +
                / %td.qnt-count.col-md-2
                /   / - s = rand(12)
                /   / %a.incr-btn{:href => "#"} -
                /   / = link_to '-', edit_line_item_path(li), remote: true
                /   / %input.quantity.form-control{:type => "text", :value => "#{s}"}/
                /   / %a.incr-btn{:href => "#"} +

                /   = simple_form_for(li, remote: true) do |f|
                /     = f.error_notification
                /     / = f.button :submit, '-', class: 'incr-btn'
                /     = f.submit '-', class: 'btn-primary', style: 'width: 25px'
                /     = f.input_field :quantity, readonly: true, id: "quantity_#{li.id}", class: 'quantity form-control'
                /     = f.submit '+', class: 'btn-primary', style: 'width: 25px'

                / %td{ :class => "total", id: "total_#{li.id}" }
                /   = number_to_currency li.total_price, unit: 'руб.'

                %td.delete
                  %center{style: 'padding-top: 12px;'}
                    / %i.icon-delete
                    / = link_to image_tag('delete.png'), li, method: :delete, remote: true, class: 'delete_item', :data => { :confirm => 'Удалить из корзины товар?' }
                    = link_to li, method: :delete, remote: true, :data => { :confirm => 'Удалить из корзины товар?' } do
                      %i.icon-delete
                    &nbsp;
                    &nbsp;
                / %td
                /   - if li.product
                /     = link_to add_to_wishlist_path(id: li.product.id), method: :post, class: "btn btn-success btn-xs btn-block" do
                /       Отложить



      / Sidebar
      .col-lg-3.col-md-3

        / %h3 Итого
        %form.cart-sidebar{:method => "post"}
          .cart-totals
            %table
              %tbody
                %tr
                  %td Подытог
                  %td{ :class => "total align-r" }
                    = number_to_currency @cart.total_price

        %h3 Есть скидочный купон?
        = form_tag(coupons_check_path, remote: true) do
          .coupon
            .form-group
              %label.sr-only{:for => "coupon-code"} Введите код купона
              - @cart.coupon ? code = @cart.coupon.code : code = ""
              %input#coupon-code.form-control{:value => code, :name => "code", :placeholder => "Введите код купона", :type => "text"}/
            #coupon_message
            %input.btn.btn-primary.btn-sm.btn-block{:name => "apply-coupon", :type => "submit", :value => "Применить купон"}/

        #total_price_with_coupon{:style => "display: none;"}
          %form.cart-sidebar
            .cart-totals
              %table
                %tbody
                  %tr
                    %td Итого с купоном
                    %td{ :class => "total align-r total_price_with_coupon" }
                      = number_to_currency(@cart.total_price true)

        %br
        %h3 Доставка
        / %a.panel-toggle{:href => "#calc-shipping"}
        /   %h3 Расчет доставки
        / #calc-shipping.hidden-panel.calc-shipping
        #calc-shipping.calc-shipping
          = form_tag calculate_shipping_path, remote: true, id: 'shipping_form' do
            .form-group
              .select-style
                %select{:name => "region", :id => 'select_region'}
                  / %option Московская область
                = hidden_field_tag :region_title
            .form-group
              / %label.sr-only{:for => "state"} Регион
              / %input#state.form-control{:name => "state", :placeholder => "Регион", :type => "text"}/
              .select-style
                %select{:name => "location", :id => 'select_location'}
                  / %option Москва
                = hidden_field_tag :city_title
            / .form-group
            /   %label.sr-only{:for => "postcode"} Индекс
            /   %input#postcode.form-control{:name => "postcode", :placeholder => "Индекс", :type => "text"}/
            / %input.btn.btn-primary.btn-sm.btn-block{:name => "update-totals", :type => "submit", :value => "Показать варианты доставки"}/
            / %input.btn.btn-primary.btn-sm.btn-block{:name => "update-totals", :type => "submit", :value => "Обновить расчет"}/
        #shipping_select_price

        %h3 Итого
        %form.cart-sidebar{:method => "post"}
          .cart-totals
            %table
              %tbody
                / %tr
                /   %td Подытог
                /   %td{ :class => "total align-r total_price" }
                /     = number_to_currency @cart.total_price
                / %tr.devider
                /   %td Доставка
                /   %td.align-r Бесплатно
                %tr
                  %td Сумма заказа
                  %td{ :class => "total align-r total_price total_price_with_coupon" }
                    = number_to_currency @cart.total_price
                %tr
                  %td Доставка
                  / %td{ :class => "total align-r total_price price_of_shipping" }
                  %td{ :class => "total align-r price_of_shipping" }
                    = number_to_currency @cart.price_of_shipping
            / %input.btn.btn-primary.btn-sm.btn-block{:name => "update-cart", :type => "submit", :value => "Обновить коризну"}/
            / %input.btn.btn-success.btn-block{:name => "to-checkout", :type => "submit", :value => "Оформить заказ"}/

        = link_to new_order_path, method: :get, class: 'btn btn-success btn-block disabled make_order' do
          Оформить заказ

/ Shopping Cart Close
/ Catalog Grid
%section.catalog-grid
  .container
    %h2.primary-color Новинки
    .row
      - Product.limit(4).each do |product|
        / Tile
        .col-lg-3.col-md-4.col-sm-6
          .tile
            .price-label= number_to_currency product.price, unit: 'руб.'
            %a{:href => "#"}
              %img{:alt => "1", :src => "#{product.image_url}"}/
            .footer
              %a{:href => "#"}= product.title
              %span
              .tools
                .rate
                  %span.active
                  %span.active
                  %span.active
                  %span
                  %span
                / Add To Cart Button
                %a.add-cart-btn{:href => "#"}
                  %span Купить
                  %i.icon-shopping-cart
                / Share Button
                .share-btn
                  .hover-state
                    %a.fa.fa-facebook-square{:href => "#"}
                    %a.fa.fa-twitter-square{:href => "#"}
                    %a.fa.fa-google-plus-square{:href => "#"}
                  %i.fa.fa-share
                / Add To Wishlist Button
                %a.wishlist-btn{:href => "#"}
                  .hover-state Сравнить
                  %i.fa.fa-plus

app/views/carts/show.old.html.haml
.container.main-container
  .row
    .col-lg-3.col-md-3.col-sm-12
      = render 'best_seller'
    .clearfix.visible-sm
    / Cart
    .col-lg-9.col-md-9.col-sm-12
      .col-lg-12.col-sm-12
        %span.title КОРЗИНА
      .col-lg-12.col-sm-12.hero-feature
        %table.table.table-bordered.tbl-cart
          %thead
            %tr
              %td.hidden-xs Картинка
              %td Наименование
              %td Размер
              %td Цвет
              %td.td-qty Количество
              %td Цена
              %td Подытог
              %td Удалить
          %tbody
            - @cart.line_items.each do |li|
              %tr
                %td.hidden-xs
                  = link_to li.product do
                    = image_tag li.product.image_url, height: 47, width: 47
                %td
                  = link_to li.product.title, li.product
                %td
                  %select{:name => ""}
                    %option{:selected => "selected", :value => ""} S
                    %option{:value => ""} M
                %td -
                %td
                  / %input.input-qty.form-control.text-center{:name => "", :type => "text", :value => "#{li.quantity}"}/
                %td.price=number_to_currency(li.total_price)
                %td=number_to_currency(li.total_price)
                %td.text-center
                  %a.remove_cart{:href => "#", :rel => "2"}
                    %i.fa.fa-trash-o
              
            %tr
              %td{:align => "right", :colspan => "6"} Total
              %td.total{:colspan => "2"}
                %b= number_to_currency(@cart.total_price)
        .row
          .col-md-2
            = link_to root_path, class: 'btn btn-primary' do
              %i.fa.fa-arrow-circle-left
              Продолжить покупки
          .col-md-1
            = button_to 'Очистить', @cart, method: :delete, data: { confirm: 'Точно?' }, class: 'btn btn-primary'
          .col-md-3
            = button_to new_order_path, method: :get, class: 'btn btn-primary' do
              Чекаут
              %i.fa.fa-arrow-circle-right
    / End Cart