config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/contacts'
  get 'static_pages/about_us'
  get 'static_pages/payments'

  get '3b5fe44d4592.html' => "files#show"

  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV['ADMIN_LOGIN'] && password == ENV['ADMIN_PASSWORD']
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

  resources :orders do
    member do
      post :repeat
      post :cancel
    end
  end

  get 'orders_exchange/1с' => 'orders#exchange_1с'

  resources :line_items do
    collection do
      get :add_to_cart
    end
  end

  namespace :payments do
    post :result
    post :success
    post :cancel
  end
  resources :carts

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}

  get '/account' => 'users#show', as: 'account'

  scope module: 'admin', path: 'admin' do
    resources :producers
    resources :messages
    resources :characteristic_names
    resources :characteristic_values
    resources :characteristics_group_vls
    resources :characteristics_group_rows
    resources :characteristics_groups
    resources :product_characteristics
    resources :posts
    resources :stocks
    resources :parts
    resources :people
    resources :discounts
    resources :home_page_banners
  end

  namespace :admin do
    resource :dashboard
    resources :deals
    resources :tizers
    resources :banners
    resources :orders do
      member do
        post :cancel
        post :ship
      end
    end
    resources :users
    resources :projects
    resources :coupons
    resources :special_offers
    resources :imports do
      collection do
        patch :proccess
      end
    end
    resources :products do
      collection do
        post :sort
      end
    end
    resources :categories do
      post :sort, on: :collection
      resources :products do
        post :sort, on: :collection
      end
    end
    resources :pages do
      post :sort, on: :collection
    end
    root 'categories#index'
  end
  # mount Ckeditor::Engine => '/ckeditor'
  resources :pages
  resources :deals, only: [:show, :index]
  resources :products, only: [:show] do
    collection do
      post :sort, :import
      get :compare, :import, :parser
    end
    member do
      get :add_to_compare, :remove_from_compare
    end
  end

  get :search, to: 'categories#search', as: 'searches'
  get 'searches/show'

  get 'wishlist/index'
  post 'wishlist/add_to_wishlist/:id' => 'wishlist#add_to_wishlist', as: 'add_to_wishlist'
  delete 'wishlist/destroy/:id' => 'wishlist#destroy', as: 'destroy_from_wishlist'

  post 'coupons/check' => 'coupons#check', as: 'coupons_check'

  post 'messages/create' => 'messages#create', as: 'create_message_from_form'
  post 'calculate_shipping/calculate' => 'calculate_shipping#calculate', as: 'calculate_shipping'
  post 'calculate_shipping/select_price_of_shipping' => 'calculate_shipping#select_price_of_shipping', as: 'select_price_of_shipping'
  get 'posts/show/:id' => 'posts#show', as: 'posts_show'
  get 'posts/index' => 'posts#index', as: 'posts_index'
  resources :categories, only: [:show, :index] do
    resources :products, only: [:show]
  end
  root 'welcome#index'
end

app/models/characteristic_name.rb
class CharacteristicName < ActiveRecord::Base
  has_many :through_product_characteristics
  has_many :products, through: :through_product_characteristics
  has_many :characteristic_values
end

app/controllers/admin/characteristic_names_controller.rb
class Admin::CharacteristicNamesController < Admin::BaseController
  before_action :set_characteristic, only: [:show, :edit, :update, :destroy]

  # GET /characteristics
  def index
    @characteristics = CharacteristicName.all
  end

  # GET /characteristics/1
  def show
  end

  # GET /characteristics/new
  def new
    @characteristic = CharacteristicName.new
  end

  # GET /characteristics/1/edit
  def edit
  end

  # POST /characteristics
  def create
    @characteristic = CharacteristicName.new(characteristic_params)

    if @characteristic.save
      redirect_to @characteristic, notice: 'Characteristic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /characteristics/1
  def update
    if @characteristic.update(characteristic_params)
      redirect_to @characteristic, notice: 'Characteristic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /characteristics/1
  def destroy
    @characteristic.destroy
    redirect_to characteristics_url, notice: 'Characteristic was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic
      @characteristic = CharacteristicName.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def characteristic_params
      params.require(:characteristic).permit(:title)
    end
end

app/views/admin/characteristic_names/_form.html.haml
= simple_form_for(@characteristic) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title

    = f.association :characteristic_values, label_method: :value, input_html: { class: 'select2'}

  .form-actions
    = f.button :submit, "Готово", class: 'btn btn-success'

app/views/admin/characteristic_names/edit.html.haml
= render 'form'

= link_to 'Показать все', characteristic_names_path, class: 'btn btn-default'

app/views/admin/characteristic_names/index.html.haml
%h1
  Названия характиристик
  = link_to 'Новая характеристика', new_characteristic_name_path, class: 'btn btn-success'

%table.table.table-stripped.table-bordered.datatable

  %thead
    %tr
      %th id
      %th Характеристика
      %th Значения
      / %th
      %th
      %th

  %tbody
    - @characteristics.each do |characteristic|
      %tr
        %td= characteristic.id
        %td= characteristic.title
        %td
          - characteristic.characteristic_values.each do |cv|
            = "#{cv.value}, "
        / %td= link_to 'Показать', characteristic, class: 'btn btn-default'
        %td= link_to 'Редактировать', edit_characteristic_name_path(characteristic), class: 'btn btn-default'
        %td= link_to 'Удалить', characteristic, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/admin/characteristic_names/new.html.haml
= render 'form'

= link_to 'Показать все', characteristic_names_path, class: 'btn btn-default'

app/views/admin/characteristic_names/show.html.haml
%p#notice= notice

%p
  %b Характеристика:
  = @characteristic.title

= link_to 'Редактировать', edit_characteristic_name_path(@characteristic), class: 'btn btn-default'
\|
= link_to 'Показать все', characteristic_names_path, class: 'btn btn-default'